version: 2  

workflows:
  version: 2
  zachs_cool_workflow:
    jobs:
      - zachs-awesome-build

jobs:
  zachs-awesome-build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          #Add command name and bash commands to execute
          name: Enter command description
          command: echo "Add command here"
  zachs-epic-deploy:
      working_directory: ~/project
      docker:
      - image: circleci/node:8
      steps:
      - checkout
      - run:
          name: Deployment
          command: echo "SUCCESS - App deployment completed"